language: node_js
sudo: false
node_js:
  - "6"
cache:
  directories:
    - $HOME/.npm
    - travis_phantomjs
env:
  global:
    - BIN="node" ISTANBUL=false OPTION=""
    - SAUCE_LABS=false SAUCE_USERNAME="jhkwon"
    - secure: "JtQEkddlQTAT48Fv0ekXICoi3AL2Iu/EikwANMhmjpBo8Gl/HKVBAUTi4+1kLsEt0owrID4wlEQvs2RS0TzdGTCnkEkQ2z5P8NKwNK68IFvoxb5NCLjjfsylOD0WBwuUq/4d1ZnIx7r2wQMNRaPMgzrPpTlTpqj7CvVfTBhr8PB14rT4VHK7WBwWkYDBZR+QYUIrmI5JGQeQvErpgBS14T5eJlGWAYS3ny1HNlcGxLlfrQpccWdF+gvKv8tYmn/peCSZoIGjljzO0hl8GC+pkHkbhpL6heiw8Ddgpb9aQV6NgJzOqlAPzjVpCG2AymbAnz7K3a1ZeA/d9UnnvA3+/kRnVQ/LdC9OqI+crrp/hpqsRSGbyL3TzT8lsqAXwKryUVFDocxW24F+n7ZddT4bbaRJoi4YWAIeqnmymbokmRZcxpqSgof5OmrthY7+WTpR0wH8h6N7H6UMTXdolLFZYX1IZcBVNfYuoQFo0+LlxH9qDzkUmOn2vmP9wk/Gt8km3qPQE8jQOC7VR9ZdFziGQ8+oQalu9RHZNLr59qFtpGAh1jmeK8h6+eXSf1XE5ZguBM5VClgIKbPB267p+pcvznWlMBebw0S/5MG4FNfoYr0a79tOW444OnSyzAogId1eJIka32UrMtD/luF545yk0zS+hUFbvB4LVPKbcVkhqWE="
  matrix:
    -
    - BIN="phantomjs"
    - SAUCE_LABS=true
matrix:
  include:
    - node_js: "4"
      env:
git:
  depth: 10
branches:
  only:
    - master
    - /^build-.*$/
before_install:
  # Upgrade PhantomJS to v2.1.1.
  - "export PHANTOMJS_VERSION=2.1.1"
  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
  - "phantomjs --version"

  # Use exact Node version.
  - "nvm use $TRAVIS_NODE_VERSION"

  # Setup npm.
  - "npm set loglevel error"
  - "npm set progress false"
  - "npm i -g npm@\"^2.0.0\""

  # Remove code skipped on the coverage run.
  - |
      PATTERN[0]="|\s*while\s*\([^)]+\)\s*\{\s*iteratee\(index\);\s*\}|"
      PATTERN[1]="|\s*else\s*\{\s*assocSet\(data\b[\s\S]+?\}|"
      PATTERN[2]="|\bindex,\s*iterable\)\s*===\s*false\)[^}]+?(break;)|"
      PATTERN[3]="|\bcase\s+(?:dataView|promise|set|map|weakMap)CtorString:.+|g"
      PATTERN[4]="|\s*if\s*\(cache\.size\b[\s\S]+?\}|"
      PATTERN[5]="|\s*if\s*\(\!lodashFunc\)\s*\{\s*return;\s*\}|"
      PATTERN[6]="|\s*define\([\s\S]+?\);|"
      PATTERN[7]="|\s*root\._\s*=\s*_;|"

      if [ $ISTANBUL == true ]; then
        set -e
        for PTRN in ${PATTERN[@]}; do
          node ./test/remove.js "$PTRN" ./lodash.js
        done
      fi

  # Use lodash-cli from GitHub.
  - "git clone --depth=10 --branch=build-5124 git://github.com/junghyun87/lodash-cli ./node_modules/lodash-cli"
  - "mkdir -p ./node_modules/lodash-cli/node_modules/lodash && cd $_ && cp ../../../../lodash.js ./lodash.js && cp ../../../../package.json ./package.json"
  - "cd ../../ && npm i --production && cd ../../"

script:

  # Test in Node.js and PhantomJS.
  - "[ $ISTANBUL == true ]    || node ./node_modules/lodash-cli/bin/lodash -o ./dist/lodash.js"
  - "[ $ISTANBUL == true ]    || (node ./node_modules/lodash-cli/bin/lodash modularize exports=node -o ./ && node ./node_modules/lodash-cli/bin/lodash -d -o ./lodash.js)"
  - "[ $ISTANBUL == true ]    || [ $SAUCE_LABS == true ] || cd ./test"
  - "[ $ISTANBUL == true ]    || [ $SAUCE_LABS == true ] || $BIN $OPTION ./test.js ../lodash.js"
  - "[ $ISTANBUL == true ]    || [ $SAUCE_LABS == true ] || [ $TRAVIS_SECURE_ENV_VARS == false ] || $BIN $OPTION ./test.js ../dist/lodash.min.js"

  # Test in Sauce Labs.
  - "[ $SAUCE_LABS == false ] || node ./node_modules/lodash-cli/bin/lodash core -o ./dist/lodash.core.js"
  - "[ $SAUCE_LABS == false ] || npm run build"
  - "[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name=\"lodash tests\"     runner=\"test/index.html?build=../dist/lodash.js&noglobals=true\"     tags=\"development\""
  - "[ $SAUCE_LABS == false ] || $BIN ./test/saucelabs.js name=\"lodash tests\"     runner=\"test/index.html?build=../dist/lodash.min.js&noglobals=true\" tags=\"production\""
